include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: true
    indentation:
      enabled: true
      line_length: 1
      type: tab